### ISSUE TITLE
Need more understanding & more examples

### ISSUE THREAD

**Issue by karishmapujara** [gsuitedevs/android-samples#102]
Hello

Can you guys update the sample app in android for more details.
Like
1) CreateFileActivity
2) EditMetadataActivity
3) InsertUpdateCustomPropertyActivity
4) PinFileActivity
5) QueryFilesActivity
6) QueryFilesWithTitleActivity
7) RetrieveContentsActivity
8) RetrieveMetadataActivity

It will be helpful for more developers. Because Google Drive API is deprecated and we must migrate to the Drive REST API.

**Comment by rbstarbuck** [comment]
Apologies for the inconvenience, but these sample apps will likely not be updated due to the deprecation of the API. For samples relevant to migrating to the REST API, we recommend checking the REST API Java wrapper documentation:
https://developers.google.com/resources/api-libraries/documentation/drive/v3/java/latest/
